resources:
- name: cf-for-k8s-ci
  type: git
  icon: github
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-for-k8s
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    paths:
    - ci/**
- name: statsd_exporter
  type: git
  source:
    uri: git@github.com:prometheus/statsd_exporter
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
    tag_regex: ^v0\.[0-9]*\.[0-9]*$
- name: cf-k8s-prometheus
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-k8s-prometheus
    private_key: ((cf_for_k8s_readonly_deploy_key.private_key))
- name: statsd_exporter-cf-for-k8s-registry-image
  type: registry-image
  source:
    repository: cloudfoundry/statsd_exporter-cf-for-k8s
    username: ((dockerhub.username))
    password: ((dockerhub.password))
jobs:
- name: build-statsd_exporter-cf-for-k8s-image
  plan:
  - in_parallel:
    - get: cf-for-k8s-ci
    - get: statsd_exporter
      trigger: true
    - get: cf-k8s-prometheus
  - task: generate-image-labels-file
    file: cf-for-k8s-ci/ci/tasks/generate-oci-image-labels/task.yml
    input_mapping:
      source-repo: statsd_exporter
    output_mapping:
      labels: statsd-exporter-labels
  - task: build-statsd_exporter-cf-for-k8s-image
    privileged: true
    input_mapping:
      dockerfile: cf-k8s-prometheus
      context: statsd_exporter
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: dockerfile
      - name: context
      outputs:
      - name: image
      caches:
      - path: cache
      run:
        path: build
      params:
        DOCKERFILE: dockerfile/exporters/statsd_exporter/Dockerfile
        CONTEXT: context/.
  - put: statsd_exporter-cf-for-k8s-registry-image
    params:
      image: image/image.tar
