---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
- name: source-repo
- name: cf-for-k8s-ci

outputs:
- name: labels

run:
  path: cf-for-k8s-ci/ci/tasks/generate-oci-image-labels/task.sh
