---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.11.0
directories:
- path: config/capi/_ytt_lib/capi-k8s-release
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/capi-k8s-release
      ref: d98bece861c024df201b4ac8978f62861029c366
    includePaths:
    - templates/**/*
    - values/**/*
- path: config/networking/_ytt_lib/cf-k8s-networking
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: 99de0eaab6f1bd368140329b94204472d15134eb
    includePaths:
    - config/*
    - config/crd/**/*
    - config/routecontroller/**/*
- path: config/logging/_ytt_lib/cf-k8s-logging
  contents:
  - path: .
    githubRelease:
      slug: cloudfoundry/cf-k8s-logging
      tag: 0.5.0
      disableAutoChecksumValidation: true
- path: config/metrics/_ytt_lib/metric-proxy
  contents:
  - path: .
    githubRelease:
      slug: cloudfoundry/metric-proxy
      tag: 1.0.1
      disableAutoChecksumValidation: true
- path: config/uaa/_ytt_lib/uaa
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry/uaa
      ref: v74.29.0
    includePaths:
    - k8s/templates/**/*
- path: config/kpack/_ytt_lib/kpack
  contents:
  - path: .
    githubRelease:
      slug: pivotal/kpack
      tag: v0.1.4
      disableAutoChecksumValidation: true
    includePaths:
    - release-*.yaml
# the components in this section below are handled by their corresponding build scripts
# the manual param tells vendir to not override/touch the contents of these config/_ytt_lib/<eirini|minio|postgres> directories
- path: config/eirini/_ytt_lib
  contents:
  - path: eirini
    manual: {}

- path: config/minio/_ytt_lib
  contents:
  - path: minio
    manual: {}

- path: config/postgres/_ytt_lib
  contents:
  - path: postgres
    manual: {}

- path: config/quarks-secret/_ytt_lib
  contents:
    - path: quarks-secret
      manual: {}

# When adding or updating a helm chart to our set of components:
# 1. Navigate Chart.yaml in the chart source repo.
# 2. Note the `version` property specified on the Chart resource.
# 3. Use the `git blame` tool to find the latest commit that bumped the verion.
# 4. The SHA of the commit that bumped the version will be the SHA you use as the 'ref' of the git section below.
# 5. Also make note of the version in a comment.
- path: build/minio/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: 921eb8a969fb9d7b7b7d13904f740c76748ec2c9 # version: 5.0.30
    includePaths:
    - stable/minio/**/*

- path: build/eirini/_vendir
  contents:
  - path: .
    githubRelease:
      slug: cloudfoundry-incubator/eirini-release
      tag: v2.0.0
      disableAutoChecksumValidation: true
      unpackArchive:
        path: eirini.tgz
- path: build/postgres/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/bitnami/charts
      ref: e0c026c74b1efa60fa7b142be5e877e5b200c869 # version: 10.1.1
    includePaths:
    - bitnami/postgresql/**/*

- path: build/quarks-secret/_vendir
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry-incubator/quarks-secret
      ref: 4171053d17e66a93044795924abdca66cac09785 # version: 1.0.744
    includePaths:
    - deploy/helm/quarks-secret/**/*
