#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"eirini-api"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"opi"}),expects="1+"
      -
        #@overlay/replace
        image: #@ data.values.images.eirini.opi
        #@overlay/match missing_ok=True
        args: ["connect", "--config", "/etc/eirini/config/api.yml"]

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"eirini-task-reporter"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"task-reporter"}),expects="1+"
      -
        #@overlay/replace
        image: #@ data.values.images.eirini.task_reporter
        #@overlay/match missing_ok=True
        args: ["connect", "--config", "/etc/eirini/config/task-reporter.yml"]

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"instance-index-env-injector"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"instance-index-env-injector"}),expects="1+"
      -
        #@overlay/replace
        image: #@ data.values.images.eirini.instance_index_env_injector
        #@overlay/match missing_ok=True
        args: ["connect", "--config", "/etc/eirini/config/instance-index-env-injector.yml"]

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"eirini-event-reporter"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"event-reporter"}),expects="1+"
      -
        #@overlay/replace
        image: #@ data.values.images.eirini.event_reporter
        #@overlay/match missing_ok=True
        args: ["connect", "--config", "/etc/eirini-event-reporter/config/events.yml"]

#@overlay/match by=overlay.subset({"kind":"Job", "metadata":{"name":"eirini-app-migration"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"migration"}),expects="1+"
      -
        #@overlay/replace
        image: #@ data.values.images.eirini.migration
