#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#! TODO: Resolve migration path: https://cloudfoundry.slack.com/archives/C8RU3BZ26/p1617043838026700

#@ def rename_registry_credentials():
#@overlay/match missing_ok=True
registry_secret_name: app-registry-credentials
#@ end

#@overlay/match by=overlay.subset({"kind": "ConfigMap", "metadata":{"name":"api"}})
#@yaml/text-templated-strings
---
data:
  #@overlay/replace via=lambda eirini_config_map_content,_: yaml.encode(overlay.apply(yaml.decode(eirini_config_map_content), rename_registry_credentials()))
  api.yml:

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata": {"name":"registry-credentials"}})
---
metadata:
  #@overlay/replace
  name: app-registry-credentials