#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@overlay/match by=overlay.subset({"kind": "ValidatingWebhookConfiguration", "metadata":{"name": "eirini-resource-validator-hook"}})
---
webhooks:
#@overlay/match by="name"
- name: resource-validator.eirini.cloudfoundry.org
  clientConfig:
    #@overlay/replace
    caBundle: #@ base64.encode("{}".format(data.values.resource_validator_certificate.ca))
