#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! This certificate will cause cert-manager to create the secret istio-ingressgateway-certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: system-cert-manager
  namespace: istio-system
spec:
  secretName: cf-system-cert
  commonName: #@ 'api.' + data.values.system_domain
  dnsNames:
  - #@ 'api.' + data.values.system_domain
  - #@ 'uaa.' + data.values.system_domain
  - #@ 'login.' + data.values.system_domain
  issuerRef:
    name: #@ data.values.istio_cert_issuer_name
    kind: #@ data.values.istio_cert_issuer_kind

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workloads-cert-manager
  namespace: istio-system
spec:
  secretName: cf-workloads-cert
  dnsNames:
  #@ for/end domain in data.values.app_domains:
  - #@ "*." + domain
  issuerRef:
    name: #@ data.values.istio_cert_issuer_name
    kind: #@ data.values.istio_cert_issuer_kind
