#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/namespaces.star", "system_namespace", "workloads_namespace")

#! this gateway is used to expose CF services in the cluster, externally
#@ load("gateway.lib.yml", "gateway")
--- #@ gateway(data.values.system_domain, data.values.app_domains, system_namespace(), workloads_namespace(), data.values.gateway.https_only)

#! This will set overlay a static IP for the istio load balancer.
#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name": "istio-ingressgateway"}})
---
#@ if data.values.load_balancer.static_ip:
spec:
  #@overlay/match missing_ok=True
  loadBalancerIP: #@ data.values.load_balancer.static_ip
#@ end
