#@ load("/namespaces.star", "workloads_namespace")

#@ def build_version():
#@   return "1.7.3"
#@ end

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: restart-workloads
  namespace: #@ workloads_namespace()
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-workloads
  namespace: #@ workloads_namespace()
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    verbs: ["get", "patch", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-workloads
  namespace: #@ workloads_namespace()
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-workloads
subjects:
  - kind: ServiceAccount
    name: restart-workloads
    namespace: #@ workloads_namespace()
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-workloads
  namespace: istio-system
rules:
  - apiGroups: ["apps", "extensions", ""]
    resources: ["daemonsets","pods","deployments","configmaps"]
    verbs: ["get", "patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-workloads
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-workloads
subjects:
  - kind: ServiceAccount
    name: restart-workloads
    namespace: #@ workloads_namespace()
---
apiVersion: batch/v1
kind: Job
metadata:
  name: #@ "restart-workloads-for-istio" + build_version().replace(".", "-")
  namespace: #@ workloads_namespace()
  labels:
    cloudfoundry.org/istio_version: #@ build_version()
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: restart-workloads
      restartPolicy: Never
      containers:
        - name: roll
          image: cloudfoundry/cf-k8s-networking-upgrade-sidecars@sha256:b381197b0b0d67dff969e02c4dabda3a7304ca923c691d4da3c5509c880ed6b0
          env:
          - name: ISTIO_VERSION
            value: #@ build_version()
