#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:6f765726dd17b0ba39d77d95e972c0e3893811e4450277414bd7ef58156de385
  - image: gcr.io/paketo-community/python@sha256:5e3c2c38a6ded39c780a164d3ac20f9d4880be43fad10a108a95ad19f0450366
  - image: gcr.io/paketo-buildpacks/java@sha256:72aa5986b46e23e755a4201845a55d3a872aa907a5a29a41bf4eb02abdd47888
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:59c498f9d0187311f299dcb5666db5c6c209105170bc81b4e3ef32de009d4539
  - image: gcr.io/paketo-buildpacks/go@sha256:29f3b58497cac958c18ec0646264d532de7c5b5505081b7e5f41366d009f34e3
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:6505a502162e05bba166f9f2c0546f0aba558f54f070febc1c091ea5b903a1e3
  - image: gcr.io/paketo-buildpacks/php@sha256:5a043a43e4198ae6073f726b50dfcc3b49e2f895969c0ea040739c84098ecb87
  - image: gcr.io/paketo-buildpacks/procfile@sha256:cc3910850249adb0b7b2f6850a362dbfbfad1df976b8736ac2c90ff70093fb4e

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:00bb593f6bdf2032e357377ec3f4c5fef0dff0c7eca6bbaaab5287dc236a9501"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:c1e58d7b2c665430ba8e5f277580922cd7304cdbeb269f66e5191a32069ed04f"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
