#@ load("@ytt:data", "data")
#@ load("/namespaces.star", "workloads_staging_namespace")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: cf-buildpack-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/ruby@sha256:aa5e88c30bfedf9e28145d1c32ae2397bf9aad8c204b4c2a98e6811a59003c7d
  - image: gcr.io/paketo-community/python@sha256:e6546f3072c49336ce99a2d8297716b748a69da9128c5afb1606c2b73a18a317
  - image: gcr.io/paketo-buildpacks/java@sha256:dee1582f6ef4e3579810df0360a02d25f3d5cac168519c49ec9a725d238e7700
  - image: gcr.io/paketo-buildpacks/nodejs@sha256:5b1ce5f3093eaf9a1a210c9080f7a7539d3bdd5c98e80dba3fd77a52faf5f1e6
  - image: gcr.io/paketo-buildpacks/go@sha256:913f17254fea069c8ff8b1e47e6367dec689a7ecc497be1a30fd8f042a1daf26
  - image: gcr.io/paketo-buildpacks/dotnet-core@sha256:766c3a800cc69b80e079960dc52af3b22c71fe07dd43ba728a9b9e72fd5873d5
  - image: gcr.io/paketo-buildpacks/php@sha256:91e5a561758f818c16060007f885e5b59e7f1a323bf887c2183a02d2d560f107
  - image: gcr.io/paketo-buildpacks/procfile@sha256:bf6a4265db23ae25b34d402cd24e04c36dccdf24d6a6b9297f1d154a9d0b8062

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "index.docker.io/paketobuildpacks/build@sha256:20c46d84f1b369f09b33f5708edefc93d5b22e760c9ea6ad6cffac315f845d8d"
  runImage:
    image: "index.docker.io/paketobuildpacks/run@sha256:f368234d3c8ff28d66ee66ffc3bd463ce3983e5bd79a3fdf9749de7afb4900b0"

---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: cf-default-builder
  namespace: #@ workloads_staging_namespace()
spec:
  tag: #@ "{}/cf-default-builder".format(data.values.app_registry.repository_prefix)
  serviceAccount: cc-kpack-registry-service-account
  stack:
    name: bionic-stack
    kind: ClusterStack
  store:
    name: cf-buildpack-store
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/ruby
  - group:
    - id: paketo-buildpacks/dotnet-core
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/go
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-community/python
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/php
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/nginx
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/httpd
    - id: paketo-buildpacks/procfile
      optional: true
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
