#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata": {"name": "cf-db-postgresql"}}),expects="0+"
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: cf-db-postgresql
          image: #@ data.values.images.postgres.postgres
