#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cf-blobstore-minio"}}),expects="0+"
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: minio
          image: #@ data.values.images.minio.minio