platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-for-k8s-ci

inputs:
  - name: cf-for-k8s-ci

run:
  path: cf-for-k8s-ci/ci/tasks/cf-k8s-networking/create-pr.sh

params:
  GITHUB_KEY:
  BRANCH:
  GITHUB_TITLE:
  GITHUB_BODY:
