#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cf-quarks-secret"}}),expects="0+"
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: quarks-secret
          image: #@ data.values.images.quarks_secret.quarks_secret
